# Generated by Django 6.1.1 on 2026-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stocktransaction_products_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='type',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
