# Generated by Django 6.1.1 on 2026-09-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3),
        ),
    ]
